# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"

defaultJvmOptions: -XX:+UseG1GC -XX:MaxRAMPercentage=70 -XX:InitialRAMPercentage=70 -Dscala.concurrent.context.minThreads=8
resources:
  limits:
    cpu: "2"
    memory: 2048Mi
  requests:
    cpu: "0.5"
    memory: 1536Mi

metrics:
  enable: false
  release: prometheus-grafana-monitoring
  interval: 30s

persistence:
  databaseName: cantonnet_scan
  schema: scan
  host: postgres
  port: 5432
  user: cnadmin
  secretName: "postgres-secrets"

migration:
  id: 0

failOnAppVersionMismatch: true

spliceInstanceNames:
  networkName: "Splice"
  networkFaviconUrl: "https://www.hyperledger.org/hubfs/hyperledgerfavicon.png"
  amuletName: "Amulet"
  amuletNameAcronym: "AMT"
  nameServiceName: "Amulet Name Service"
  nameServiceNameAcronym: "ANS"
# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:

# k8s tolerations for all deployed pods (optional)
# tolerations:
