# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"

cluster:
  fixedTokens: false

defaultJvmOptions: -XX:+UseG1GC -XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=75 -Dscala.concurrent.context.minThreads=8
resources:
  limits:
    cpu: 3
    memory: 4096Mi
  requests:
    cpu: 1
    memory: 4096Mi

metrics:
  enable: false
  release: prometheus-grafana-monitoring
  interval: 30s

persistence:
  databaseName: cantonnet_sv
  schema: sv
  host: postgres
  port: 5432
  user: cnadmin
  secretName: "postgres-secrets"

migration:
  id: 0
  migrating: false
  attachPvc: true
# pvc used for migrations
pvc:
  volumeStorageClass: standard-rwo

failOnAppVersionMismatch: true

spliceInstanceNames:
  networkName: "Splice"
  networkFaviconUrl: "https://www.hyperledger.org/hubfs/hyperledgerfavicon.png"
  amuletName: "Amulet"
  amuletNameAcronym: "AMT"
  nameServiceName: "Amulet Name Service"
  nameServiceNameAcronym: "ANS"
# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:

# k8s tolerations for all deployed pods (optional)
# tolerations:
