sequencer:
  persistence:
    host: sequencer-pg
    port: 5432
    secretName: sequencer-pg-secret
    databaseName: sequencer_MIGRATION_ID
  driver:
    type: "cometbft"
    host: "global-domain-MIGRATION_ID-cometbft-cometbft-rpc"
    port: 26657
mediator:
  persistence:
    # replace MIGRATION_ID with the current migration ID of the global synchronizer
    host: mediator-pg
    port: 5432
    secretName: mediator-pg-secret
    databaseName: mediator_MIGRATION_ID
nodeIdentifier: YOUR_SV_NAME
# DOMAIN_BOOTSTRAP_START
# Set this to false only for initial onboarding (must be true for synchronizer migrations and disaster recovery)
disableAutoInit: true
# DOMAIN_BOOTSTRAP_END
